server:
  port: 8086

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 47.110.83.145:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins:
              - "http://localhost:8080"
              - "http://localhost:8082"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
      routes:
        - id: file_route
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: core_route
          uri: lb://core-service
          predicates:
            - Path=/core/**
      discovery:
        locator:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"